### ISSUE TITLE
Allow large file input boxes

### ISSUE THREAD

**Issue by johnwiseheart** [palantir/blueprint#1112]
Basically to do this would mean adding something along the lines of
```css
.pt-file-upload-input {
  &.pt-large {
    &:after {
      height: $pt-input-height-large;
      line-height: $pt-button-height-large;
    }
  }
}
```

I don't have time to actually add it and PR right now, but if this is still here when I have free time, I'll attempt it.
