### ISSUE TITLE
[Table] Table doesn't expand to the right height on Safari

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#1345]
### Bug report

- __Package version(s)__: Table 1.16.0
- __Browser and OS versions__: Mac Safari 10.11, iPad Safari, iOS 10 

![image](https://user-images.githubusercontent.com/24398123/28185211-6526865e-67cb-11e7-8252-be13674f4f08.png)

**Comment by cmslewis** [comment]
Can't repro / fixed as far as I can tell. (Safari 11.0, BP Table v1.27.0)

**Comment by pselden** [comment]
This does happen if the element containing the table doesnt have a fixed height:

For example, on the docs page if you remove the style rule:

```css
[data-page-id="table-js"] .bp-table-container, [data-page-id="table-js"] .docs-react-example {
    width: 100%;
    /* height: 300px; */
}
```

It will look like this on Chrome:
![screen shot 2017-11-15 at 2 27 09 pm](https://user-images.githubusercontent.com/709282/32855925-38980542-ca11-11e7-9ae6-29866bb3cdf5.png)

And like this on Safari:
![screen shot 2017-11-15 at 2 28 37 pm](https://user-images.githubusercontent.com/709282/32855939-499b2f40-ca11-11e7-9f5a-2ea9e234de61.png)

I found 2 "fixes", but I'm not sure how it affects other things:

1) Removing flex-direction: column on .bp-table-container
2) Removing height: 100% on .bp-table-quadrant-main
