### ISSUE TITLE
[Popover] Appears after "closed" by hovering over container when animation is not complete

### ISSUE THREAD

**Issue by dmackerman** [palantir/blueprint#1385]
### Bug report

- __Package version(s)__:  Latest
- __Browser and OS versions__:  Mac OSX Sierra, Chrome Latest

#### Steps to reproduce

1. Go to `Menu` documentation. 

See this GIF for behavior:

![menus](https://user-images.githubusercontent.com/289938/28632485-92154f46-71e5-11e7-9793-7c6595ad59a9.gif)

This seems like a bug to me, but maybe it's the intended behavior. This has some pretty bad UX implications for us as we use Popover in our main nav, and often run into Menus re-appearing when the mouse travels over the area before the animation is "complete".

Sounds like you guys are working on `Popover2` - just something to keep in mind if this was a nagging issue that got punted because of a rewrite.

**Comment by llorca** [comment]
Definitely not intended behavior, submenus need a lot of work: https://github.com/palantir/blueprint/issues/898 https://github.com/palantir/blueprint/issues/849 https://github.com/palantir/blueprint/issues/847

Does `Popover2` with Popper makes that any better out of the box @giladgray?

**Comment by dmackerman** [comment]
@llorca FWIW the behavior isn't limited only to submenus. Happens with any `Popover`.

**Comment by llorca** [comment]
Right, I'm able to repro with `InteractionKind.HOVER` but it's trickier than submenus: I have to instantly hover back on the popover area before the animation ends, which requires a lot of dexterity. I doubt this is a serious problem, whereas it seems much easier to end up in this situation with submenus.

**Comment by giladgray** [comment]
`Popover2` will have literally zero effect on `MenuItem` because those will continue to use the original `Popover` internally.

**Comment by FezVrasta** [comment]
Looks like the menu item is hidden with a CSS transition to `opacity: 0` and if you hover over it before it is completely removed (after the transition) it will appear again because it thinks you just moved the mouse accidentally outside the menu.

A possible solution could be to set `pointer-events: none` to the menu while the opacity transition is in progress

**Comment by dmackerman** [comment]
@FezVrasta If you look at the `_popover.scss` file, similar code actually already exists:

```scss
// _popover.scss, line 94
.pt-transition-container {
  @include fade-transition();
  z-index: $pt-z-index-overlay;

  &:focus {
    outline: none;
  }

  // popover content should ignore pointer events during a popover's exit transition
  &.pt-popover-leave .pt-popover-content {
    pointer-events: none;
  }
}
```
