### ISSUE TITLE
[Table] Fix column-header ghost-cell borders

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#1511]
### Bug report

- __Package version(s)__: v1.26.0

#### Steps to reproduce

1. Enable ghost cells in a viewport that extends beyond the last column.

#### Actual behavior

Missing horizontal borders below column header cells.

![image](https://user-images.githubusercontent.com/443450/29797853-625835d2-8c0e-11e7-8f3d-fec78dd7140e.png)

#### Expected behavior

Horizontal borders below column header cells.

![image](https://user-images.githubusercontent.com/443450/29797846-57c8b434-8c0e-11e7-9b05-3b71ae67e6ec.png)

```scss
.bp-table-column-headers {
  /* BEFORE: box-shadow: 0 1px 0 0 rgba(16, 22, 26, 0.15); */
}

.bp-table-column-headers .bp-table-header {
  /* BEFORE: box-shadow: inset -1px 0 0 rgba(16, 22, 26, 0.15); */ 
  box-shadow: inset -1px 0 0 rgba(16, 22, 26, 0.15), 0 1px 0 rgba(16, 22, 26, 0.15);
}
```
