### ISSUE TITLE
[Labs/Popover2] regression from original Popover for .pt-button-group

### ISSUE THREAD

**Issue by bbenezech** [palantir/blueprint#1517]
`react-popper` adds an extra wrapper tag:

https://github.com/souporserious/react-popper/blob/ef520ee1213f30d3af3f10c6f5b4a04a888deb73/src/Manager.jsx#L36

**But**

`.pt-button-group` expects its **direct children** to be `.pt-button` or `.pt-popover-target` : 
https://github.com/palantir/blueprint/blob/dd90bfa0943dd6ac2ea1d233162cc3c21aa4e701/packages/core/src/components/button/_button-group.scss#L102-L116

Setting `rootElementTag` to `false`, which should remove `react-popper`'s Manager's wrapper does not work:

```
invariant.js:44 Uncaught Error: Manager.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

It's because `children` is an array of 2 React components:

https://github.com/palantir/blueprint/blob/dd90bfa0943dd6ac2ea1d233162cc3c21aa4e701/packages/labs/src/components/popover/popover2.tsx#L268-L288

https://github.com/souporserious/react-popper/blob/ef520ee1213f30d3af3f10c6f5b4a04a888deb73/src/Manager.jsx#L38-L40

Of course I hacked something in my own project and Popover2 is in Lab so I have no expectation or need for this getting fixed before it is moved to Core to replace Popover for `2.0`.

Thanks for the great work, as usual!

**Comment by bbenezech** [comment]
For anyone looking for a quick fix, this should help:

```scss
.pt-button-group:not(.pt-minimal) {
  span:not(:first-child) .pt-popover-target .pt-button {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }

  span:not(:last-child) .pt-popover-target .pt-button {
    margin-right: -$button-border-width;
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }
}
```

**Comment by bbenezech** [comment]
I also fixed a separator issue with `.minimal`:

```scss
.pt-button-group {
  &.pt-minimal {
    > :last-child .pt-popover-target .pt-button {
      margin-right: 0;
      &::after {
        display: none;
      }
    }
  }
}

```
