### ISSUE TITLE
pt-rtl className support for EditableCell is not fully supported

### ISSUE THREAD

**Issue by rzteux** [palantir/blueprint#1533]
### Bug report

- __Package version(s)__: blueprintjs/table 1.24.1
- __Browser and OS versions__: Chrome 61 on Ubuntu 16.04 LTS x64

#### Steps to reproduce

1. Render an EditableCell in a Table component with className set to pt-rtl
1. double-click on the cell to enter in edit mode

#### Actual behavior

When cell is rendered, text is well right aligned. But when we double click it to enter in edit mode, rtl is lost !
Behavior is correct when using classic input with such class :)

#### Expected behavior

When double clicking on EditableCell, text to edit should be aligned to right

**Comment by rzteux** [comment]
Hacky workaround found :
Override .pt-rtl class in scss with
```scss
.pt-rtl {
    .pt-editable-input {
      text-align: right !important;
      width: 200px !important;
    }
  }
```

Since in EditableText, width is fixed by default to the lenght of the text to edit so text-align override will do nothing without width override
