### ISSUE TITLE
Default TabPanel margin-top too large

### ISSUE THREAD

**Issue by forman** [palantir/blueprint#193]
### Bug Report

- __Package version(s)__: 1.0.1
- __Browser and OS versions__: Chromium (Electron)

#### Describe the issue:

The default TabPanel margin-top seems too large.

#### Actual behavior:

TabPanel has a margin-top of 20px.

#### Expected behavior:

```css
[role=tabpanel] {
    margin-top: 5px;  /* or so */
}
```

**Comment by forman** [comment]
I don't consider this a problem, as it can easily be adjusted. Same for Tab components:

```css
    [role=tab] {
        margin-right: 5px;
    }
```
