### ISSUE TITLE
Incorrect Icon on Checkbox

### ISSUE THREAD

**Issue by mickaelmartinsdev** [palantir/blueprint#2312]
Hello,

Since I have update to blueprintjs 2.0, the checkbox icon isn't good. I have a E6D8 instead tick icon.

Can-you help me ? 

I use this

import "@blueprintjs/core/lib/css/blueprint.css";
import { Checkbox } from "@blueprintjs/core";

Thank-you

**Comment by giladgray** [comment]
@mickaelmartinsdev we pulled the icon styles and fonts to a separate `@blueprintjs/icons` package. see the code samples in http://blueprintjs.com/docs/v2/#blueprint/getting-started, they now include `blueprint-icons.css`.

i'll update the What's New page accordingly.

**Comment by mickaelmartinsdev** [comment]
Hi Gilda,

When I import  "@blueprintjs/icons/lib/css/blueprint-icons.css"; I have this exception : uncaught exception: Package not found @blueprintjs/icons.
I bundle my application with fusebox.

Furthermore, I already include icon with fusebox : 
fs.copySync("node_modules/@blueprintjs/icons/resources", `${buildDir}/resources`);
And icon (ex : arrow-right) is well displayed. 

 Have you got an idea to help me ? I have the unicode instead of the sign tick in Checkbox.

**Comment by mickaelmartinsdev** [comment]
I found the bug, in blueprint.css

```css
 .pt-control.pt-checkbox input:checked ~ .pt-control-indicator::before, .pt-control.pt-checkbox input:indeterminate ~ .pt-control-indicator::before{
    content:""; }
  .pt-control.pt-checkbox input:indeterminate ~ .pt-control-indicator::before{
    content:""; }
```
The content of the css isn't weel defined. 
 
How I can fix this bug ?
