### ISSUE TITLE
Import just the code for svg icons. Propose.

### ISSUE THREAD

**Issue by ghost** [palantir/blueprint#2412]
Maybe this code in `@blueprintjs\core\src\components\icon\_icon.scss` is just what you want from there. 

```css
svg.pt-icon {
  // respect dimensions exactly
  flex: 0 0 auto;
  vertical-align: top;
  // inherit text color by default
  fill: currentColor;
}
```

But if I import that file in my `index.scss` it imports also these: `@import "~@blueprintjs/icons/src/icons";` which I don't want in my final index.css.

Is there a way to import just that code for svg icons?

Maybe a new file named: `_svgIcon.scss`?
