### ISSUE TITLE
'invert' option on Tooltip

### ISSUE THREAD

**Issue by silverwind** [palantir/blueprint#2733]
#### Environment

- __Package version(s)__: `@blueprintjs/core@3.0.1`
- __Browser and OS versions__: Firefox on macOS

#### Feature request

The `Tooltip` component currently shows a light background on the dark theme and a dark background on the light theme. Would love to see a option to disable this inversion for aesthetical reasons and to be consistent with `Popover`. I've attempted to do it via CSS, but it seems to not be trivial.

#### Examples

The default value should be `true` to represent the current behaviour. Example which turns it off:

```js
<Tooltip content="Tooltip that matches Popover!" invert={false}>
    <Button>Click me</Button>
</Tooltip>
```

**Comment by giladgray** [comment]
@silverwind this is part of the design of the system. you can set `Classes.DARK` in a light theme to invert it, but not the other way.

**Comment by silverwind** [comment]
Yes, I was actually interested in dark tooltips on the dark theme because those bright white ones seem rather distracting. Think I'll go with CSS similar to this:

````css
.bp3-dark .bp3-tooltip {
  box-shadow:0 0 0 1px rgba(16, 22, 26, 0.1), 0 2px 4px rgba(16, 22, 26, 0.2), 0 8px 24px rgba(16, 22, 26, 0.2);
}

.bp3-dark .bp3-tooltip .bp3-popover-content {
  background: #394b59;
  color: #f5f8fa;
}

.bp3-dark .bp3-tooltip .bp3-popover-arrow:before {
  box-shadow:1px 1px 6px rgba(16, 22, 26, 0.2);
}

.bp3-dark .bp3-tooltip .bp3-popover-arrow-border {
  fill: #10161a;
}

.bp3-dark .bp3-tooltip .bp3-popover-arrow-fill {
  fill: #394b59;
}
````
