### ISSUE TITLE
Migrating to 3.0: Icon Buttons have extra padding on right side 

### ISSUE THREAD

**Issue by cmslewis** [palantir/blueprint#2769]
#### Environment

- __Package version(s)__: `@blueprintjs/core 3.2.0`
- __Browser and OS versions__: Max OS X Sierra, Chrome 68.0.3440.84

#### Steps to reproduce

Buttons with an icon but no text have extra right padding in Blueprint 3.X (and maybe in 2.X too, since that's when the SVG icon refactor occurred?).

#### Actual behavior

From the [Button docs](http://blueprintjs.com/docs/#core/components/button):

![screen shot 2018-08-07 at 9 21 37 am](https://user-images.githubusercontent.com/443450/43788854-62ba7854-9a23-11e8-8a14-0c0f91759dc2.png)
![screen shot 2018-08-07 at 9 22 09 am](https://user-images.githubusercontent.com/443450/43788855-63d28772-9a23-11e8-9b16-f4570b574ec4.png)

#### Expected behavior

![image](https://user-images.githubusercontent.com/443450/43788948-94e6d002-9a23-11e8-8b89-b2eab427ca93.png)

![image](https://user-images.githubusercontent.com/443450/43788959-9d1c0c10-9a23-11e8-887d-372182715152.png)

#### Possible solution

Given that:
- We'd need to detect when `.bp3-button-text` is `:empty` in order to remove the `margin-right` from the _preceding_ `svg` element, and
- CSS selectors don't let you peek ahead like that,

It follows that:
- A pure CSS solution here would presumably require us to either (1) add a new `bp3-button-empty` CSS class to the root button element, or (2) move the `margin-right` on the `svg` to a `margin-left` on `bp3-button-text`, then do this:

    ```scss
    .bp3-icon + .bp3-button-text {
        margin: 7px; // or whatever SCSS variable math yields this value
    }
   
    .bp3-button-text:empty {
        margin-left: 0;
    }
    ```

I propose (2).
