### ISSUE TITLE
Blueprint without icon fonts

### ISSUE THREAD

**Issue by rgbkrk** [palantir/blueprint#3012]
#### Environment

- __Package version(s)__: 3.7.0
- __Browser and OS versions__: Chrome 69, macOS 10.13.6

#### Question

We're hoping to incorporate blueprint for use in our apps, which span electron apps (custom desktop app, atom plugin), python servers (jupyter extension), and next.js. This requires having / loading the CSS for blueprint components. Within https://github.com/nteract/nteract/pull/3412 we've made the blueprint css get "vendorized" so that we can use it freely across various components and apps. One issue I'm worried about though -- the icon font needs to be loaded. I noticed in [the Icon docs](https://blueprintjs.com/docs/#core/components/icon) these lines

> Blueprint 2.0 introduced SVG icon support and moved icon resources to a separate `@blueprintjs/icons package`. The Icon component renders SVG paths and the icon classes are no longer used by any Blueprint React component. **Icon font support has been preserved but should be considered a legacy feature that will be removed in a future major version**.

Which made me hopeful that I wouldn't have to worry about incorporating the icon font. A dive into other CSS within blueprint core leads me to the (likely necessary) classes that use the icon for `::before` and other pseudo-selectors where it makes complete sense:

```css
.bp3-menu-item::before {
    line-height: 1;
    font-family: "Icons16", sans-serif;
    font-size: 16px;
    font-weight: 400;
    font-style: normal;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    margin-right: 7px;
  }
```

```
  .bp3-select::after {
    line-height: 1;
    font-family: "Icons16", sans-serif;
    font-size: 16px;
    font-weight: 400;
    font-style: normal;
    -moz-osx-font-smoothing: grayscale;
    -webkit-font-smoothing: antialiased;
    content: "";
  }
```

There are a few others it can be found in as well. How likely can we adopt blueprint if our requirement is that we don't dictate webpack settings or font loading on the consumers of our components?

cc @alexandercbooth @emeeks
