### ISSUE TITLE
Separate _reset.scss from blueprint.css

### ISSUE THREAD

**Issue by gnestor** [palantir/blueprint#3194]
Related to https://github.com/palantir/blueprint/issues/244

After https://github.com/palantir/blueprint/pull/2366, there are still a handful of global styles in https://github.com/palantir/blueprint/blob/develop/packages/core/src/_reset.scss that can affect an app using blueprint. It would be nice if these styles could get compiled to a reset.css file that's separate from blueprint.css so that apps that provide their own reset stylesheet or styles for things like body `*` are can choose not to import them.

Our current workaround is to patch blueprint.css and check it into git...

**Comment by gnestor** [comment]
I think these rules are the only ones that we collide with:

```scss
body {
  @include base-typography();
  color: $pt-text-color;
  font-family: $pt-font-family;
}

p {
  margin-top: 0;
  margin-bottom: $pt-grid-size;
}

small {
  font-size: $pt-font-size-small;
}

strong {
  font-weight: 600;
}

::selection {
  background: $pt-text-selection-color;
}
```
