### ISSUE TITLE
<Divider /> component CSS not appearing, not sure if bug

### ISSUE THREAD

**Issue by havesomeleeway** [palantir/blueprint#3297]
#### Environment

- __Package version(s)__: 
    "@blueprintjs/core": "^3.11.0",
- __Browser and OS versions__: 
Google Chrome: Version 71.0.3578.98 (Official Build) (64-bit)
OS: Mojave 10.14.2 

#### Question

![screenshot 2019-01-19 at 4 00 25 pm](https://user-images.githubusercontent.com/25948209/51424053-7b435280-1c03-11e9-991d-870c642c2a95.png)

I made use of the `<Divider />` component within my component. As you can see, it's showing up in the inspector. However for some reason, the CSS attributed to the divider isn't showing up.

I'm expecting the css from the `<Divider />` component to be appearing. i.e.
```css
// Copyright 2018 Palantir Technologies, Inc. All rights reserved.
// Licensed under the terms of the LICENSE file distributed with this project.

@import "../../common/variables";

$divider-margin: $pt-grid-size / 2 !default;

.#{$ns}-divider {
  margin: $divider-margin;
  // since the element is empty, it will occupy minimal space and only show
  // the appropriate border based on direction of container.
  border-right: 1px solid $pt-divider-black;
  border-bottom: 1px solid $pt-divider-black;


  .#{$ns}-dark & {
    border-color: $pt-dark-divider-black;
  }
}
```

My code is straightforward.

```jsx
import React from "react";
import {Button, Navbar, Divider} from "@blueprintjs/core";
// import { Link } from "react-router-dom";
import {Alignment} from "@blueprintjs/core/lib/cjs/common/alignment";


const NavBar = () => {
    return (
        <Navbar>
            <Navbar.Group align={Alignment.LEFT}>
                <Navbar.Heading>
                    App
                </Navbar.Heading>
                <Button icon="home" text="One" intent="minimal"/>
                <Button icon="upload" text="Two" intent="minimal"/>
                <Button icon="chart" text="Three" intent="minimal"/>
                <Button icon="bank-account" text="Four" intent="minimal"/>
                <Divider/>
                    <Button icon="cog" intent="minimal"/>
                    <Button text="Logout" intent="primary"/>
            </Navbar.Group>
        </Navbar>
    );
};

export default NavBar
```

Has anyone else experienced this?
