### ISSUE TITLE
AnchorButton alignText left remains centered

### ISSUE THREAD

**Issue by nerdstep** [palantir/blueprint#3704]
#### Environment

- __Package version(s)__: 3.18.0
- __Browser and OS versions__: Chrome 76.0.3809.100 on Windows 10

If possible, link to a minimal repro (fork [this code sandbox](https://codesandbox.io/s/nko3k41y60)): 

https://codesandbox.io/s/peaceful-perlman-op2064jyq

#### Steps to reproduce

1. Use `AnchorButton` component with `alignText="left"`

#### Actual behavior

Button text is centered.

#### Expected behavior

Button text should be left-aligned.

#### Possible solution

Add `*-align-left` class to provide specificity.

```scss
  &.#{$ns}-align-left,
  .#{$ns}-align-left& {
    text-align: left;
  }
```
