### ISSUE TITLE
DateRangePicker/Input prev button misaligned

### ISSUE THREAD

**Issue by johanwilson** [palantir/blueprint#4082]
#### Environment

- __Package version(s)__: @blueprintjs/datetime 3.16.0
- __Browser and OS versions__: Chrome | Win10

If possible, link to a minimal repro: [Sandbox](https://codesandbox.io/s/blueprint-sandbox-tm8ry)

#### Steps to reproduce

See sandbox or DateRangePicker/DateRangeInput docs

#### Actual behavior

Previous button overlap the month select element

#### Expected behavior

Align without overlap

#### Possible solution

It seems to originate from this code, remove it or replace by 0px
https://github.com/palantir/blueprint/blob/4873110b2a6720dc736e2544d7408197928cf996/packages/datetime/src/_daterangepicker.scss#L12-L15

```css
.bp3-daterangepicker .DayPicker:first-of-type .bp3-datepicker-navbar {
    left: 5px;
}
```
