### ISSUE TITLE
MultiSelect: Adding a Custom Class to .bp3-popover-content

### ISSUE THREAD

**Issue by kittles04** [palantir/blueprint#4222]
#### React/Chrome Environment

- __Package version(s)__: 3.13.4 
- __Operating System__:Catalina 
- __Browser name and version__: latest Chrome 

Trying to customize styles on my MultiSelect Component, specifically the popover. I want to be able to add custom styling to the element that has the class  `.bp3-popover-content` without changing `.bp3-popover-content directly`.  

These styles I want to have in a separate custom class: 

```css
.bp3-popover-content{
    min-width: 500px;
    overflow-x: hidden;
    overflow-y: scroll;
    scrollbar-width: none;
    transform: translateZ(0);
    max-height: 250px;
    min-height: 250px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    list-style-type: none;
    margin-top:10px;
    .top-list {
      overflow-y: scroll;

      .selected-fadeout {
        opacity: 0.5;
      }
    }
```

custom styling needs to be added to parents of ItemRenderer.
Tried adding a custom class to ItemRenderer but its not afffecting the popover container like I want it to. It seems like I would need a parent CSS Selector but there are no parent selectors in CSS

I looked at the documentation to see if MultiSelect could add a custom class to the top of the PopOver DOM Tree but I didn't see one. 

Is there something that I'm missing here? Is there a way to do this through BluePrint or should this be a feature request for BP to be able to add a custom class to the top of the popover DOM Tree?
 
![Screen Shot 2020-07-10 at 7 47 46 PM](https://user-images.githubusercontent.com/48726084/87211197-5efb1000-c2e6-11ea-915e-720a5a92f1b5.png)

ItemRenderer allows me to add custom classes to the div.categories element but I need a custom class higher in the DOM Tree.
