### ISSUE TITLE
[Checkbox | Breadcumbs] Not fully compatible with CSP

### ISSUE THREAD

**Issue by ejose19** [palantir/blueprint#4347]
#### Steps to reproduce

- On the server serving the html, set header ```Content-Security-Policy``` with value ```img-src 'self'```
- Use a checkbox component and check it

#### Actual behavior

Checkbox ticks (either checked or indeterminate) do not render, due the data:image being blocked

#### Expected behavior

Ticks should work like the rest of the library

#### Note

I see this behaviour is a side-effect of #2709

There are 2 workarounds for this

1. Adding ```data:``` to the ```img-src``` policy, however that may not be desired as it can't be limited to just ```data:image/svg+xml``` and mitigations provided by CSP are reduced.

2. Override background-image set by blueprint in the following way:

- Add to your public/img the following 2 svgs (checked and indeterminate)

checked.svg
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M12 5c-.28 0-.53.11-.71.29L7 9.59l-2.29-2.3a1.003 1.003 0 00-1.42 1.42l3 3c.18.18.43.29.71.29s.53-.11.71-.29l5-5A1.003 1.003 0 0012 5z" fill="white"/>
</svg>
```
indeterminate.svg
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
  <path fill-rule="evenodd" clip-rule="evenodd" d="M11 7H5c-.55 0-1 .45-1 1s.45 1 1 1h6c.55 0 1-.45 1-1s-.45-1-1-1z" fill="white"/>
</svg>
```

- Add to your main css file

```css
.bp3-control.bp3-checkbox input:checked ~ .bp3-control-indicator::before {
  background-image: url('/img/checked.svg') !important;
}

.bp3-control.bp3-checkbox input:indeterminate ~ .bp3-control-indicator::before {
  background-image: url('/img/indeterminate.svg') !important;
}
```

or if using sass

```scss
.bp3-control.bp3-checkbox input {
  &:checked ~ .bp3-control-indicator::before {
    background-image: url('/img/checked.svg') !important;
  }
  &:indeterminate ~ .bp3-control-indicator::before {
    background-image: url('/img/indeterminate.svg') !important;
  }
}
```

I see Breadcumbs are also affected since #2742, however the same 2 workarounds works for it as well, if more components are changed to inline svg then 2nd solution will become way too cumbersome.
