### ISSUE TITLE
Some mechanism for letting EditableText shrink to its content size when not editing

### ISSUE THREAD

**Issue by robertf224** [palantir/blueprint#4543]
So this mostly already happens, but the min-width on the inner `span` is set to `80px`.  Have a UI like this:
<img width="244" alt="Screen Shot 2021-02-25 at 11 45 32 AM" src="https://user-images.githubusercontent.com/671815/109186952-6ed54080-775f-11eb-8243-a21652e4daf9.png">

Without doing some css hacking to unset the min-width, it ends up looking like this:
<img width="225" alt="Screen Shot 2021-02-25 at 11 49 29 AM" src="https://user-images.githubusercontent.com/671815/109187133-99bf9480-775f-11eb-9e5b-e7a180b5b600.png">

css hacking I'm doing is:
```scss
.display-name-value {
    max-width: 250px;

    > :last-child {
        // Need our EditableTexts to contract to their content size
        /* stylelint-disable declaration-no-important */
        min-width: unset !important;
        /* stylelint-enable declaration-no-important */
    }
}
```

but that's obviously really flaky, so was hoping for a more formal way to remove/lower the min-width (`unset` isn't necessarily correct because you get into a weird spot if you don't have a placeholder, but want the ability to make it lower than `80px` at least)
