### ISSUE TITLE
Support inline styles for Tooltips/Popovers

### ISSUE THREAD

**Issue by hellochar** [palantir/blueprint#480]
I'd like to have a `tooltipStyles` props on Tooltips/Popovers so I can dynamically set e.g. max-width of a tooltip. 

Perhaps an even more general solution is to expose general HTMLProps object as a Tooltip prop?

**Comment by nschwan94** [comment]
I'm finding the background color of tooltips prohibitively difficult to implement. Why? I've used tooltipClassName and both a <style> tag and an external sass stylesheet to try and override the background color, but to no avail.

**Comment by llorca** [comment]
@nschwan94 You have to override two properties to change both the background of the tooltip and tooltip arrow. Looks like this:

```css.scss
.pt-tooltip {
  .pt-popover-content {
    background: $your-color;
  }

  .pt-popover-arrow-fill {
    fill: $your-color;
  }
}
```
