### ISSUE TITLE
Switch component with innerLabel has incorrect focus outline 

### ISSUE THREAD

**Issue by lwouis** [palantir/blueprint#5131]
#### Environment

- __Package version(s)__: I'm using 3.52.0, but it seems to be present in latest since I can reproduce it on the demo page
- __Operating System__: macOS 10.15.7 (19H114)
- __Browser name and version__: Chrome 97.0.4692.71 (Official Build) (x86_64)

#### Code Sandbox

https://blueprintjs.com/docs/#core/components/switch

#### Steps to reproduce

1. Go on the [`Switch` component demo page](https://blueprintjs.com/docs/#core/components/switch)
2. Tab to the last component with an inner text
3. The focus outline is wrong: it has a bump where the alternate text exists (hidden)

#### Actual behavior

![image](https://user-images.githubusercontent.com/106195/154213879-9ba9c550-0321-4f00-92de-c9e9b69bca85.png)
![image](https://user-images.githubusercontent.com/106195/154213887-8bbfd07b-8002-4689-8fa0-ff7be3d0bf17.png)

#### Expected behavior

The outline to hug the oval correctly:

![image](https://user-images.githubusercontent.com/106195/154214536-68c52959-7ea5-4274-b8df-c60fcab42fe7.png)
![image](https://user-images.githubusercontent.com/106195/154214542-60882abf-d549-47ae-a0b3-e0f679ddae78.png)

#### Possible solution

I fixed it locally with this extra CSS:

```css
.bp3-control.bp3-switch input:checked ~ .bp3-control-indicator .bp3-control-indicator-child:first-child {
  transform: initial;
}
.bp3-control.bp3-switch .bp3-control-indicator-child:first-child,
.bp3-control.bp3-switch input:checked ~ .bp3-control-indicator .bp3-control-indicator-child:last-child {
  transform: scale(1, 0);
}
```
