### ISSUE TITLE
CSS for using react-select?

### ISSUE THREAD

**Issue by DrewDennison** [palantir/blueprint#597]
Hello,

I'm using Blueprint and also react-select. Do you have any CSS to make the react-select inputs look like regular `<inputs>`?

Thanks!

**Comment by dmackerman** [comment]
Here's what we're using for now.

```scss
.Select-control {
  @include pt-input();
  height: 30px;
  padding-right: 5px;
  line-height: 28px;

  &:hover {
    box-shadow: 0 0 0 0 rgba(19, 124, 189, 0),
      0 0 0 0 rgba(19, 124, 189, 0),
      inset 0 0 0 1px rgba(16, 22, 26, 0.15),
      inset 0 1px 1px rgba(16, 22, 26, 0.2);
  }
}

.Select-input {
  height: 30px;
}

.Select-placeholder {
  height: 30px;
}

.Select--multi .Select-value {
  margin: 4px 3px 0 0;
  height: 24px;
  padding: 0;
  line-height: 24px;
  font-size: 12px;
}

.Select-placeholder,
.Select--single > .Select-control .Select-value {
  line-height: 30px;
}

.Select--multi .Select-value-label {
  padding: 0 10px;
}

.is-focused:not(.is-open) > .Select-control {
  box-shadow: input-transition-shadow($input-shadow-color-focus, true), $input-box-shadow-focus;
}
```
