### ISSUE TITLE
Use HTML5 dialog element for Portals

### ISSUE THREAD

**Issue by justinbhopper** [palantir/blueprint#6229]
My team is facing issues with automation because all content rendered via portals (dialogs, popovers) end up rendered on the DOM in a way that our automation tools have a hard time associating the portaled content with the content that it belonged to.  

For example, the automation tool finds it difficult to associate the click of a MenuItem that a given Select field was rendering.  It doesn't understand that the MenuItem is related to the same form that the Select is within.

I'm wondering if html5's `<dialog>` can be of use here.  The main purpose of Portal is to help fix issues with z-index rendering, and that's exactly the same purpose for `<dialog>`.  By rendering the content within a `<dialog>`, you'll achieve the same benefits.

Combined with the new `PortalProvider`, we could enable this feature where-ever we want (globally, or just in specific instances).

Example:
```ts
<PortalProvider useDialog>
  <Select ...>
    <button>Click</button>
  </Select>
</PortalProvider>
```

Some necessary css:
```css
.bp4-dialog-portal {
  position: fixed;
  width: 100%;
  height: 100%;
  inset: 0;
  max-width: unset;
  max-height: unset;
  padding: 0;
  margin: 0;
  border: none;
  background: transparent;
  z-index: 20;
}
```

This would render:
```html
<div class="bp4-popover2-target bp4-popover2-open" role="combobox">
  <button>Click</button>
</div>
<dialog class="bp4-dialog-portal" open> <!-- Instead of a portal, we wrap the popover with dialog element -->
  <div class="bp4-overlay">
    <div class="bp4-popver2-transition-container" style="position absolute; inset: etc">
      <div class="bp4-popover2">
        <div class="bp4-popover2-content">
          <ul class="bp4-menu">...</ul>
        </div>
      </div>
    </div>
  </div>
</dialog>
```

Note from above, the overlay transition effects do not need to change at all -- I've tested this and the css transition effects still work great.
