### ISSUE TITLE
Improve selected state for editable column header in blueprint-table

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#645]
Current: 
![image](https://cloud.githubusercontent.com/assets/24398123/22754040/01ed1ffa-edf3-11e6-9e96-e6a58435e081.png)

@llorca has mocks/ideas on how to improve

**Comment by llorca** [comment]
When a cell is near the edge of the table, it's always cut off because the table is overflow hidden, and the column/row headers are always on top of cells. Not sure how to go around that

**Comment by tnrich** [comment]
We see this issue as well in multiple places within our app. Wherever there might be a non `overflow: visible`:
![image](https://user-images.githubusercontent.com/2730609/55588059-ae18c500-56e1-11e9-97ba-8f9d1e09fdd0.png)

![image](https://user-images.githubusercontent.com/2730609/55588076-b7099680-56e1-11e9-825b-40a570f267ea.png)

We're considering doing something like this: 
```css
/* override the default blueprint input focus to instead rely on an inset box shadow. This resolves any issues with overflow:hidden cutting off input box shadows */
.bp3-dark .bp3-input:focus,
.bp3-input:focus {
  box-shadow: inset 0 0 3px 1px #137cbd;
}
```
