### ISSUE TITLE
Buttons should make it easy to style overflow text with ellipses

### ISSUE THREAD

**Issue by adidahiya** [palantir/blueprint#6515]
#### Environment

- __Package version(s)__: core v5.6.0
- __Browser and OS versions__: Chrome on macOS

#### Feature request

Users often need to style Button text with `Classes.TEXT_OVERFLOW_ELLIPSIS` styling to truncate long text. This is currently somewhat cumbersome to do; we often see styles like this in a CSS module:

```scss
// in a CSS module

@use "@blueprintjs/core/lib/scss/variables" as bp;

.my-button {
 :global(.#{bp.$ns}-button-text) {
    overflow: hidden;
    text-wrap: nowrap;
    text-overflow: ellipsis;
  }
}
```

https://github.com/palantir/blueprint/issues/4460 will help with this; that will allow users to use Blueprint's utility styling class:

```tsx
<Button textClassName={Classes.TEXT_OVERFLOW_ELLIPSIS} />
```

However it would be even nicer if Buttons had a prop for this styling behavior, something like:

```tsx
<Button ellipsizeText={true} />
```

^ this prop naming attempts to match up with `<Text ellipsize={true}>`
