### ISSUE TITLE
FR: Support row and column based styling

### ISSUE THREAD

**Issue by tgreenwatts** [palantir/blueprint#930]
Currently the table is made up of `<td>`s only, so users can't easily add styling based on columns or rows themselves. 

It is possible by getting the classnames, but could be supported by BP table out of the box

Unlocks ability to provide striped styling like the HTML table supports today https://github.com/palantir/blueprint/blob/e22fa34917dc0d903243f946dea2db50616aec5b/packages/core/src/components/table/_table.scss#L102

**Comment by cmslewis** [comment]
This was/is already possible to a degree with `styledRegionGroups`, if you know exactly which rows you want to style and are working at a sufficiently small data scale that you can pass each region of interest in an array: 

```tsx
<Table
    styledRegionGroups={[
        {
            className="highlighted",
            regions: [Regions.row(0)]
        },
    ]}
/>
```

Zebra striping is also already possible via CSS:
```scss
.bp-table-zebra-striped {
  .bp-table-zebra-striped-cell-even {
    background-color: $light-gray4;
  }

  .bp-table-zebra-striped-cell-odd {
    background-color: $white;
  }
}
```
And then you can just supply those `className`s to each cell based on its `rowIndex` being odd or even.
